/**:
  ros__parameters:
    encryption_key: "robocup2023"
    port: 1234
    send_frequency: 300
    sender_queue_max_size: 5

    topics:
      - /rosout
      - /robot_state
      - /goal_pose
      - /cmd_vel
      - /pose_with_covariance
      - /debug/dsd/body_behavior/dsd_current_action
      - /debug/dsd/body_behavior/dsd_tree
      - /debug/dsd/body_behavior/dsd_stack
      - /debug/dsd/hcm/dsd_current_action
      - /debug/dsd/hcm/dsd_tree
      - /debug/dsd/hcm/dsd_stack
      - /debug/dsd/localization/dsd_current_action
      - /debug/dsd/localization/dsd_tree
      - /debug/dsd/localization/dsd_stack
      - /team_data
      - /balls_relative
      - /debug/viz_ball
      - /robots_relative
      - /gamestate
      - /animation
      - /diagnostics_agg
      - /imu/data
      - /buttons
      - /system_workload
      - /field/map
