/**:
  ros__parameters:
    encryption_key: "robocup2023"
    port: 1234
    send_frequency: 10
    sender_queue_max_size: 5

    topics:
      - /rosout
      - /robot_state
      - /goal_pose
      - /cmd_vel
      - /pose_with_covariance
      - /debug/dsd/body_behavior
      - /debug/dsd/hcm
      - /team_data
      - /balls_relative
      - /robots_relative
      - /gamestate
      - /animation
      - /diagnostics_agg
      - /joint_states
      - /imu/data
      - /buttons
      - /system_workload
