---
encryption_key: "germanopen2019"
port: 1234
send_frequency: 10
sender_queue_max_size: 5
target_ips:
  - 192.168.18.111

topics:
  - /rosout
  - /robot_state
  - /cmd_vel
  - /debug/dsd/body_behavior
  - /debug/dsd/head_behavior
  - /debug/dsd/hcm
  - /move_base_simple/goal
  - /team_data
  - /balls_relative
  - /ball_relative
  - /obstacles_relative
  - /gamestate
  - /animation/goal
  - /animation/cancel
  - /animation/status
  - /animation/result
  - /animation/feedback
  - /animation
  - /diagnostics
  - /joint_states
  - /imu/data
  - /buttons
  - /system_workload
